#!/usr/bin/env python3
"""Table 1 (cohort characteristics) from the three-hospital cohort workbook.

The workbook contains protected health information and stays OUTSIDE this repository; its path
comes from the COHORT_XLSX environment variable (see Makefile). Only counts, percentages and
medians are written to tables/table1_cohort.tex. The script also prints a cross-check against the
workbook's own pre-computed summary sheet (圖表們) so a silent column shift would be noticed.

Column semantics (sheet 基本資料): yes = {是, 有}, no = {否, 無}, blank = not recorded.
"""
from __future__ import annotations

import os
import statistics
import sys
from collections import Counter
from pathlib import Path

try:
    import openpyxl
except ImportError:  # pragma: no cover
    sys.exit("openpyxl is required: pip install openpyxl")

HERE = Path(__file__).resolve().parent
OUT = HERE / "table1_cohort.tex"
YES = {"是", "有", "有影響", "存活"}
NO = {"否", "無", "無影響", "死亡"}
HOSPITAL = {"KMUH": "KMUH", "VGHTPE": "TVGH", "TS": "TSGH"}
SPECIMEN_GROUPS = [("BALF", ["BALF"]), ("Blood", ["Blood"]), ("Sputum", ["Sputum"]),
                   ("CSF", ["CSF"]), ("Tissue", ["Tissue"]), ("Other", ["Ascites", "Pus", "Abscess"])]


def load(path: Path):
    wb = openpyxl.load_workbook(path, read_only=True, data_only=True)
    basic = [r for r in wb["基本資料"].iter_rows(values_only=True)]
    hdr = {name: i for i, name in enumerate(basic[0]) if name}
    patients = [r for r in basic[1:] if r[hdr["編碼"]] not in (None, "")]
    mngs = [r for r in wb["mNGS"].iter_rows(values_only=True)]
    mhdr = {name: i for i, name in enumerate(mngs[0]) if name}
    mrows = [r for r in mngs[1:] if r[mhdr["編碼"]] not in (None, "")]
    micro = [r for r in wb["微生物診斷資料"].iter_rows(values_only=True)]
    charts = [r for r in wb["圖表們"].iter_rows(values_only=True)]
    return hdr, patients, mhdr, mrows, micro, charts


def yes_no(values):
    yes = sum(1 for v in values if str(v).strip() in YES)
    no = sum(1 for v in values if str(v).strip() in NO)
    return yes, no, len(values) - yes - no


def pct(n: int, d: int) -> str:
    return f"{n} ({100.0 * n / d:.1f}\\%)" if d else "--"


def median_iqr(values) -> str:
    nums = []
    for v in values:
        try:
            nums.append(float(v))
        except (TypeError, ValueError):
            pass
    if not nums:
        return "--"
    q = statistics.quantiles(nums, n=4, method="inclusive")
    return f"{statistics.median(nums):.0f} ({q[0]:.0f}--{q[2]:.0f})"


def main() -> None:
    path = Path(os.environ.get("COHORT_XLSX", "")).expanduser()
    if not path.is_file():
        sys.exit(f"COHORT_XLSX does not point to the cohort workbook: {path!s}")
    hdr, patients, mhdr, mrows, micro, charts = load(path)
    n = len(patients)
    col = lambda name: [r[hdr[name]] for r in patients]

    hosp = Counter(HOSPITAL.get(str(h), str(h)) for h in col("醫院"))
    male = sum(1 for v in col("性別") if v == "男")
    icu = sum(1 for v in col("病房單位") if v == "ICU")
    pneumonia = Counter(str(v) if v else "missing" for v in col("肺炎種類"))
    specimen = Counter(str(r[mhdr["specimen_type"]]) for r in mrows)
    n_org = [int(r[mhdr["病原菌數"]]) for r in mrows if r[mhdr["病原菌數"]] not in (None, "")]
    org_zero = sum(1 for v in n_org if v == 0)

    # microbiology sheet: culture positivity, therapy change, mNGS influence, outcome (by header name)
    mic_hdr = list(micro[0])
    codes = {str(c) for c in col("編碼")}
    mic_rows = [r for r in micro[1:] if str(r[0]) in codes]   # join on patient code; drop stray rows

    def mic_col(name: str, occurrence: int = 0):
        idx = [i for i, h in enumerate(mic_hdr) if h == name][occurrence]
        return [r[idx] for r in mic_rows]

    culture_pos = sum(1 for v in mic_col("病原菌1") if v not in (None, "", "-", "－"))
    abx_change = yes_no(mic_col("微生物治療改變"))
    mngs_influence = yes_no(mic_col("mNGS是否影響"))
    change_mode = Counter(str(v).strip() for v in mic_col("治療變化方式") if v not in (None, ""))
    ventilated = yes_no(mic_col("送檢日三日內呼吸器使用"))
    died = sum(1 for v in mic_col("出院狀態") if str(v).strip() == "死亡")
    outcome_known = sum(1 for v in mic_col("出院狀態") if str(v).strip() in {"存活", "死亡"})

    comorb = [("Diabetes mellitus", "糖尿病"), ("Chronic kidney disease", "慢性腎衰竭"),
              ("End-stage renal disease on dialysis", "ESRD洗腎"), ("Liver cirrhosis", "肝硬化"),
              ("Autoimmune disease", "自體免疫疾病"), ("Active malignancy", "活動性腫瘤"),
              ("Systemic corticosteroids", "全身性類固醇"), ("ARDS on the day of sampling", "送檢日ARDS")]

    lines = []
    lines.append("% Generated by tables/make_table1.py from the cohort workbook (kept outside the repo). Do not edit by hand.")
    lines.append("\\begin{table}[p]")
    lines.append("\\centering")
    lines.append("\\caption{\\textbf{Characteristics of the three-hospital \\mngs registry.} Values are $n$ (\\%) or median (interquartile range). "
                 "\\todo{Registry of 105 specimens from which the 55- and 41-patient cohorts were drawn (Supplementary Fig.~1); restrict to the evaluation cohorts once their manifests are available. "
                 "Corticosteroid row reads both site encodings as yes; the workbook summary counts one (5.7\\%).}}")
    lines.append("\\label{tab:cohort}")
    lines.append("\\small")
    lines.append("\\begin{tabular}{lr}")
    lines.append("\\toprule")
    lines.append(f"Characteristic & All patients ($n={n}$) \\\\")
    lines.append("\\midrule")
    lines.append("\\textit{Hospital} & \\\\")
    for name in ("KMUH", "TVGH", "TSGH"):
        lines.append(f"\\quad {name} & {pct(hosp.get(name, 0), n)} \\\\")
    lines.append(f"Age, years & {median_iqr(col('年齡'))} \\\\")
    lines.append(f"Male sex & {pct(male, n)} \\\\")
    lines.append(f"Current or former smoker & {pct(yes_no(col('抽菸史'))[0], n)} \\\\")
    lines.append(f"Intensive care unit at sampling & {pct(icu, n)} \\\\")
    lines.append("\\textit{Underlying conditions} & \\\\")
    for label, key in comorb:
        y, _, miss = yes_no(col(key))
        suffix = f"$^{{\\dagger}}$" if miss else ""
        lines.append(f"\\quad {label}{suffix} & {pct(y, n - miss)} \\\\")
    lines.append("\\textit{Pneumonia category} & \\\\")
    lines.append(f"\\quad Community-acquired & {pct(pneumonia.get('CAP', 0), n)} \\\\")
    lines.append(f"\\quad Hospital- or ventilator-associated & {pct(pneumonia.get('HAP/VAP', 0), n)} \\\\")
    lines.append(f"\\quad Not classified & {pct(pneumonia.get('missing', 0), n)} \\\\")
    lines.append(f"PaO$_2$/FiO$_2$ ratio at sampling & {median_iqr(col('送檢日PF ratio'))} \\\\")
    lines.append("\\textit{\\mngs specimen} & \\\\")
    for label, keys in SPECIMEN_GROUPS:
        lines.append(f"\\quad {label} & {pct(sum(specimen.get(k, 0) for k in keys), n)} \\\\")
    lines.append(f"Organisms per \\mngs report, median (IQR) & {median_iqr(n_org)} \\\\")
    lines.append(f"\\mngs report with no organism & {pct(org_zero, n)} \\\\")
    lines.append(f"Any positive culture & {pct(culture_pos, len(mic_rows))} \\\\")
    lines.append("\\textit{Clinical course} & \\\\")
    y, _, miss = abx_change
    lines.append(f"\\quad Antimicrobial therapy changed & {pct(y, len(mic_rows) - miss)} \\\\")
    lines.append(f"\\quad \\quad Escalation & {pct(change_mode.get('升階', 0), len(mic_rows))} \\\\")
    lines.append(f"\\quad \\quad De-escalation & {pct(change_mode.get('降階', 0), len(mic_rows))} \\\\")
    y, _, miss = mngs_influence
    lines.append(f"\\quad Change attributed to \\mngs$^{{\\ddagger}}$ & {pct(y, n)} \\\\")
    y, _, miss = ventilated
    lines.append(f"\\quad Mechanical ventilation within 3 days of sampling$^{{\\dagger}}$ & {pct(y, len(mic_rows) - miss)} \\\\")
    lines.append(f"\\quad In-hospital death$^{{\\dagger}}$ & {pct(died, outcome_known)} \\\\")
    lines.append("\\bottomrule")
    lines.append("\\end{tabular}")
    lines.append("")
    lines.append("\\vspace{2pt}\\raggedright\\footnotesize $^{\\dagger}$Denominator excludes patients without a recorded value. $^{\\ddagger}$Denominator is all patients; attribution was not recorded for " + str(mngs_influence[2]) + " patients. "
                 "KMUH, Kaohsiung Medical University Hospital; TVGH, Taipei Veterans General Hospital; TSGH, Tri-Service General Hospital; "
                 "BALF, bronchoalveolar lavage fluid; CSF, cerebrospinal fluid.")
    lines.append("\\end{table}")
    OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"wrote {OUT}")

    # ---- cross-check against the workbook's own summary sheet -----------------------------
    hdr_row, val_row = charts[0], charts[1]
    summary = {str(k): v for k, v in zip(hdr_row, val_row) if k}
    checks = {
        "年齡中位數": statistics.median(float(v) for v in col("年齡") if v not in (None, "")),
        "男性(%)": round(100 * male / n, 1),
        "ICU(%)": round(100 * icu / n, 2),
        "DM(%)": round(100 * yes_no(col("糖尿病"))[0] / n, 2),
        "CKD(%)": round(100 * yes_no(col("慢性腎衰竭"))[0] / n, 2),
        "腫瘤(%)": round(100 * yes_no(col("活動性腫瘤"))[0] / n, 2),
        "CAP": pneumonia.get("CAP", 0),
        "Abx改變(%)": round(100 * abx_change[0] / (len(mic_rows) - abx_change[2]), 2),
        "mNGS影響(%)": round(100 * mngs_influence[0] / (len(mic_rows) - mngs_influence[2]), 2),
    }
    print("cross-check vs 圖表們 (computed | workbook):")
    for k, v in checks.items():
        print(f"  {k:12s} {v!s:>8} | {summary.get(k)!s:>8}")
    print("change modes:", dict(change_mode), "| survival % (workbook 存活(%)):",
          round(100 * (outcome_known - died) / n, 2), "|", summary.get("存活(%)"))


if __name__ == "__main__":
    main()
